name = "CVCData"
uuid = "09d169fb-5e1d-4706-bf8b-fe52d09f4911"
authors = ["Dohyun Kim"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
